version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo '
        global:
          scrape_interval: 5s
        scrape_configs:
          - job_name: "api-dotnet"
            static_configs:
              - targets: ["host.docker.internal:7425"]
        ' > /etc/prometheus/prometheus.yml && \
        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - observability

volumes:
  prometheus_data:
  grafana_data:

networks:
  observability:
    driver: bridge
